### ISSUE TITLE
Demonstration construction of SST2

### ISSUE THREAD

**Issue by YRdddream** [HazyResearch/ama_prompting#1]
Hi,

This work is amazing, thanks for providing the code!
I have some questions about it.
1. In Line 47 of SST2_final.py, there is no ".sample(frac=1, random_state=0)", all demonstrations seem to be arranged by their labels in the few-shot baseline.
2. For NQ and WebQs, the evaluation metric is span overlap accuracy instead of exact matching, does GPT-3 use the same metric?
3. Can I change the order of demonstrations in the prompt chain? I tried it on WSC and found that the order can affect the evaluation results.

Thanks so much

**Comment by simran-arora** [comment]
Hi, thanks for your interest in the work!

Regarding SST2 and WSC yes, the distribution over next tokens with respect to an LM can change depending on the prompt-string we're conditioning on. Feel free to make any modifications to the prompts to explore, though yes, performance may change. You may even consider aggregating over your alternate prompts in addition to the ones we provide. 

Regarding those two QA tasks, GPT-3 reports accuracy. You can find their reported metrics for all tasks on page 63 "Metric" column in the original GPT-3 paper (https://arxiv.org/pdf/2005.14165.pdf).

Please let us know if you have additional questions!!
