### ISSUE TITLE
apex==0.1 can't be installed

### ISSUE THREAD

**Issue by cooljoseph1** [HazyResearch/ama_prompting#6]

**Comment by simran-arora** [comment]
Hi, 

Can this be closed? This README includes installation instructions: https://github.com/NVIDIA/apex
Please provide more details on your setup (torch version, error messages) if you are still facing this issue.

Best,
Simran

**Comment by cooljoseph1** [comment]
The problem occurs with `pip install -r requirements.txt` where `requirements.txt` is currently
```
apex==0.1
cvxpy==1.2.1
datasets==1.4.0
dill==0.3.5.1
GPUtil==1.4.0
ipdb==0.13.9
ipython==8.5.0
matplotlib==3.5.2
more_itertools==8.14.0
networkx==2.8.5
nltk==3.7
numpy==1.23.3
pandas==1.4.2
scikit_learn==1.1.2
scipy==1.8.1
setuptools==59.5.0
snorkel==0.9.9
tensorboardX==2.5.1
tensorflow==2.9.1
tools==0.1.9
torch==1.12.1
torchtext==0.13.1
tqdm
```
It doesn't look like the code actually uses the apex requirement, so maybe you should get rid of it? If not, it would be nice to include a link to that repository in the README.

Here's the exact error message:
```
ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1
```
I'm using Linux Mint 21.1 with an x86_64 processor.

**Comment by simran-arora** [comment]
Thanks! Made the changes!
