### ISSUE TITLE
Clarify the definition of "good-quality" prompt and "imperfect" prompt

### ISSUE THREAD

**Issue by dayuyang1999** [HazyResearch/ama_prompting#7]
Dear authors,

I just want to know what is the definition of "good-quality" prompt and "imperfect" prompt. Are my understanding correct?

Good-quality prompt = prompt which mostly contains ground-truth question-answer pairs. (the answers are more tend to be correct)
imperfect prompt = prompt which contains many false question-answer pairs. (the answers are more likely to be incorrect)

Thanks,
Dylan

**Comment by simran-arora** [comment]
Hi Dylan, 

An assumption in the weak supervision framework is that the voting functions (in our case prompts) are correlated with ground truth and typically above > 50% accuracy. However, the idea is we can take many prompts that do not lead to 100% correct results, but often correct results, and aggregate them together to produce predictions that are higher quality than the individual prompts. Weak supervision helps us decide how to combine the prompts.

Hope this is helpful!
