### ISSUE TITLE
problem when run tasks/RTE_final.py

### ISSUE THREAD

**Issue by lihuiliullh** [HazyResearch/ama_prompting#8]
I follow the instructions in readme, and meet this error. Do you know how to solve it?

ama_prompting/manifest/manifest/manifest.py", line 104, in __init__
    raise ValueError(f"{list(kwargs.items())} arguments are not recognized.")
ValueError: [('session_id', None)] arguments are not recognized.

**Comment by lorr1** [comment]
You likely need an earlier version of manifest installed. v0.1.2 might be a good bet.
